apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: wildcard-tls
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  hosts:
    - "*.f5demo.local"
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: grafana-vs
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.19"
  tlsProfileName: wildcard-tls
  virtualServerName: "grafana-vs"
  iRules:
  - /Common/grafana
  pools:
  - path: /
    service: nginx-plus
    servicePort: 80

---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: prometheus-vs
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.20"
  tlsProfileName: wildcard-tls
  virtualServerName: "prometheus-vs"
  iRules:
  - /Common/prometheus
  pools:
  - path: /
    service: nginx-plus
    servicePort: 80